spring:
  application:
    name: vapp
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/vapp}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

app:
  jwt:
    secret: "change-this-very-long-secret-key"
    expiration-minutes: 1440